# Generated by Django 2.2.15 on 2022-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_statuslist_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photos')),
            ],
        ),
        migrations.RemoveField(
            model_name='statuslist',
            name='image',
        ),
        migrations.AddField(
            model_name='statuslist',
            name='image',
            field=models.ManyToManyField(blank=True, to='status.Image'),
        ),
    ]
